default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: black-apply
        name: black-apply
        entry: uv run black
        language: system
        pass_filenames: true
        types: ["python"]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: true
        types: ["python"]
        exclude: "tests/"
      - id: ruff-apply
        name: ruff-apply
        entry: uv run ruff check --fix
        language: system
        pass_filenames: true
        types: ["python"]
      - id: pip-audit
        name: pip-audit
        entry: uv run pip-audit --ignore-vuln CVE-2025-2953 --ignore-vuln CVE-2025-3730
        language: system
        pass_filenames: false