name: CI
on: push
jobs:
  test:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-test.yml@main
  lint:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-lint.yml@main
   