### This is the Terraform-generated dev-build.yml workflow for the         ### 
### timdex-embeddings-dev app repository.                                  ###
### If this is a Lambda repo, uncomment the FUNCTION line at the end of    ### 
### the document. If the container requires any additional pre-build       ### 
### commands, uncomment and edit the PREBUILD line at the end of the       ###
### document.                                                              ###

name: Dev Container Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'tests/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy (${{ matrix.variant }}) to Dev
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant: [gpu, nogpu]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Configure AWS Dev credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCT_DEV }}:role/timdex-embeddings-gha-dev

      - name: Login to Dev ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push conatiner (${{ matrix.variant }})
        run: |
          echo "### :whale: Docker Build & Publish" >> $GITHUB_STEP_SUMMARY
          make test-vars-${{ matrix.variant }}
          echo "âœ… Successfully built and deployed the ${{ matrix.variant }} container." >> $GITHUB_STEP_SUMMARY
