### This is a custom dev-build.yml workflow for the                        ### 
### timdex-embeddings-dev app repository. It is customized in order to     ###
### support parallel builds for amd64 and/or arm64 for AWS Batch compute   ###
### environments that have GPUs and compute environments that do NOT have  ###
### GPUs.                                                                  ###


name: Dev Container Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'tests/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  GHA_ROLE: "timdex-embeddings-gha-dev"
  REPOSITORY: "timdex-embeddings-dev"

jobs:
  choose-runners:
    name: Determine Runner architecture from .aws-architecture file
    runs-on: ubuntu-latest
    outputs:
      gpu_arch: ${{ steps.out.outputs.gpu_arch }}
      cpu_arch: ${{ steps.out.outputs.cpu_arch }}
    steps:
      - uses: actions/checkout@v5

      - id: out
        run: |
          GPU_ARCH=$(jq -r '.gpu // "linux/amd64"' .aws-architecture)
          CPU_ARCH=$(jq -r '.cpu // "linux/amd64"' .aws-architecture)
          echo "gpu_arch=$GPU_ARCH" >> $GITHUB_OUTPUT
          echo "cpu_arch=$CPU_ARCH" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.variant }} (${{ matrix.arch }})
    needs: choose-runners
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: gpu
            arch: ${{ needs.choose-runners.outputs.gpu_arch }}
          - variant: cpu
            arch: ${{ needs.choose-runners.outputs.cpu_arch }}
    runs-on: ${{ matrix.arch == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set Tags
        id: tags
        run: |
          KEY=${{ matrix.variant }}
          ARCH=${{ matrix.arch }}
          TAG_ARCH=$(echo "$ARCH" | cut -d'/' -f2)
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            TAG_SHA=$(echo $GITHUB_SHA | cut -c 1-8)
            TAG_PR=$GITHUB_EVENT_NAME
          else
            TAG_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-8)
            TAG_PR="PR-${{ github.event.pull_request.number }}"
          fi
          echo "arch=${ARCH}" >> $GITHUB_OUTPUT
          echo "tag_latest=latest-${TAG_ARCH}-${KEY}" >> $GITHUB_OUTPUT 
          echo "tag_sha=${TAG_SHA}-${TAG_ARCH}-${KEY}" >> $GITHUB_OUTPUT
          echo "tag_pr=${TAG_PR}-${TAG_ARCH}-${KEY}" >> $GITHUB_OUTPUT

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Configure AWS Dev credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCT_DEV }}:role/${{ env.GHA_ROLE }}

      - name: Login to Dev ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup BuildX Builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push (${{ matrix.variant }})
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile-${{ matrix.variant }}
          pull: true
          push: true
          sbom: false
          provenance: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ steps.tags.outputs.tag_latest }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ steps.tags.outputs.tag_sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ steps.tags.outputs.tag_pr }}
